### ISSUE TITLE
Error [ERR_Require_ESM] - Unraid - Bug in versions: 5.1.114-5.1.123

### ISSUE THREAD

**Issue by Sign1an** [synclounge/synclounge#1041]
### Self-Hosting

**System Details**

- Operating System: Unraid-6.10.2

**SyncLounge Details**

- Running in Docker? (Yes/No): Yes
- Using a Reverse Proxy (Yes/No): Yes
    If Yes, which Reverse Proxy (Nginx, Apache, Caddy, etc.): Swag

### Issue information

**To Reproduce**

- Install the latest version of Synclounge: linuxserver from the Unraid app library. You can also use the "latest" tag and it'll still error at start. I specifically put in 5.1.117 to show that it is still happening in that version. 

- EDIT 6/10/22: I just tested 5.1.118 and its still broken.

**Describe your bug/issue**
When attempting to install any version of Synclounge after 5.1.113, The docker container will not start due to an error. The error includes "Error [ERR_REQUIRE_ESM] : Must use import to load ES Module". I have been testing out each version since the 5.1.113 version (5.1.114, 5.1.115, 5.1.116, 5.1.117, and 5.1.118) and have been experiencing the same behavior. See screenshots below. This issue is related to #1035 which said it was fixed in 5.1.116, however, when testing, that was not the case.

![Screenshot 2022-06-05 100356](https://user-images.githubusercontent.com/53189096/172057498-ac0808e6-a71d-418b-8031-2a298ff1520a.png)
![Screenshot 2022-06-05 100427](https://user-images.githubusercontent.com/53189096/172057500-d545c97c-8e91-4255-906b-05733ef47f9b.png)

**Things I've tried**
- Completely removing the docker from the machine and re-pulling the latest tag from the App Library - **UNSUCCESSFUL**
- Repulling each specific tag from 5.1.114-5.1.118. Also tried 5.1.116 where it was mentioned that it was fixed - **UNSUCCESSFUL**
- Downgrading to 5.1.113 and turning off auto update - **SUCCESSFULLY STARTED**

**Comment by TheFiZi** [comment]
Same issue here using docker on a CentOS 8 Stream and Docker 20.10.16. The container keeps crashing in a loop. Logs say:

```
/app/node_modules/syncloungeserver/dist/socketserver/index.js:15

var _urlJoin = _interopRequireDefault(require("url-join"));

                                      ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /app/node_modules/url-join/lib/url-join.js from /app/node_modules/syncloungeserver/dist/socketserver/index.js not supported.

Instead change the require of url-join.js in /app/node_modules/syncloungeserver/dist/socketserver/index.js to a dynamic import() which is available in all CommonJS modules.

    at Object.<anonymous> (/app/node_modules/syncloungeserver/dist/socketserver/index.js:15:39)

    at Object.<anonymous> (/app/node_modules/syncloungeserver/dist/lib.js:29:44)

    at Object.<anonymous> (/app/server.js:3:26) {

  code: 'ERR_REQUIRE_ESM'
```


My script for updating/launching the container:

```bash
#!/bin/bash
# Pull the latest version
docker pull synclounge/synclounge

# Stop and remove the old container
docker stop SyncLounge
docker rm SyncLounge

# Start new container with the data mounted
docker run -d --restart unless-stopped --name=SyncLounge -p 65500:8088 -p 65499:8089 -v /var/SyncLounge/settings.json:/opt/synclounge/settings.json -e DOMAIN=mydmoain.com synclounge/synclounge
```

**Comment by marissa999** [comment]
I would assume that the issue is due to the upgrade from url-join to 5.0.0 in syncloungeserver:
https://github.com/synclounge/syncloungeserver/blob/master/package.json#L50

url-join 5.0.0 (https://github.com/jfromaniello/url-join/releases/tag/v5.0.0) seems to just have migrated their code to an ECMAScript module (https://github.com/jfromaniello/url-join/pull/76)

It seems like dependabot actually suggested that change:
https://github.com/synclounge/syncloungeserver/commit/9393d0705e0f0faabce752086ed8dfb97ec80855

I would assume that all that needs to be done is changing this so that it is a dynamic import:
https://github.com/synclounge/syncloungeserver/blob/master/src/socketserver/index.js#L6

**Comment by Sign1an** [comment]
per your recommendation above are they planning on updating the code to resolve the error so this will work on unraid?  I recently tried to update to 5.1.123 and its still broken.
