### ISSUE TITLE
Feature Request: Allow manual adjustment of sync "delay".

### ISSUE THREAD

**Issue by cecoates** [synclounge/synclounge#202]
**Is your feature request related to a problem? Please describe.**

I've been enjoying using SyncLounge to watch a movie with friends in other States while we video chat.

Our example setup:

User 1, User 2, and User 3 all login and join the same SyncLounge room.

User 1, User 2, and User 3 all join a video chat via Skype or something similar.

To avoid an audio echo, User 2 and User 3 mute their SyncLounge audio and listen via User 1's video chat.

That way we can chat during the movie without an echo. However, because SyncLounge isn't *exactly* synced, it'd be nice if the host could manually adjust the delay to account for it.

**Describe the solution you'd like**
Being able to adjust a delay up/down would be nice to more properly sync up the audio from the video chat.

**Describe alternatives you've considered**
Headsets can help avoid an audio echo, but it gets awkward when you're doing this in groups because having 2-3 people in the same room (if, let's say, there are two people at User 3's house) is a bit weird.

**Comment by ttshivers** [comment]
How do you invision this fitting in the user interface?
