### ISSUE TITLE
Switching on subtitles

### ISSUE THREAD

**Issue by NIAG247** [synclounge/synclounge#204]
When I switch on subtitles on a movie the media starts buffering significantly. With no subtitles though the media has no problem playing. The media with subtitles has such significant buffering that it appears that the pixels are misaligned. I would really appreciate any help. 
<img width="1437" alt="With subtitles" src="https://user-images.githubusercontent.com/63987071/82158067-3ef52600-983a-11ea-93c7-549fe4eb82eb.png">

**Comment by dgw** [comment]
I bet turning on subtitles makes your Plex server transcode the video to "burn in" the text, and the hardware isn't powerful enough to keep up.

**Comment by NIAG247** [comment]
Is there a way to fix this?

**Comment by varszegik** [comment]
This happened to me with other players as well, disabling hardware acceleration in the Plex server fixes it. I think this issue is not related to SyncLounge

**Comment by ttshivers** [comment]
When turning on subtitles with synclounge at the moment, they must be burned in by Plex. This effectively requires Plex to re-render the video with the subtitles on top. If your system isn't powerful enough to handle that, buffering may occur. A solution I am looking into is adding more support to synclounge web player for native subtitle playback to avoid having to burn them in.

**Comment by ttshivers** [comment]
I am beginning to work on native ASS subtitle support for the synclounge web player. I will update when done.

**Comment by ttshivers** [comment]
I have implemented native ASS subtitle support in my branch as of  ttshivers/synclounge#36
