### ISSUE TITLE
Wrong content selected for playback - same title

### ISSUE THREAD

**Issue by tpansino** [synclounge/synclounge#210]
If you haven't already, be sure to check the **How-to Report an Issue page** before reporting an issue: https://docs.synclounge.tv/how-tos/report-an-issue/

Please complete the following when reporting a bug/an issue.

### Web App
You can remove this section if your issue isn't related to the Web App

**System Details**

- Operating System: Windows 10, Ubuntu 18.04
- Web Browser name and version: Firefox 76.0.1, Chromium 81.0.4044.122

**Plex Media Server details**

- Version: 1.19.3.2764
- Operating System (Windows/Linux/Mac): Docker on Ubuntu 18.04 (linuxserver.io latest image)
- Running in Docker? (Yes/No): Yes
- Location (Local/Remote): Both
- Remote Access Enabled (Yes/No)?: Yes

**Plex Client details**

- Name: Plex Web Client
- Version: 4.30.2
- Network connection (Wired/Wifi): Both
- Platform: Windows 10, Ubuntu 18.04

### Self-Hosting
You can remove this section if your issue isn't related to Self-Hosting

**System Details**

- Operating System: Ubuntu 18.04

**SyncLounge Details**

- Running in Docker? (Yes/No): Yes
- Using a Reverse Proxy (Yes/No): Yes
    If Yes, which Reverse Proxy (Nginx, Apache, Caddy, etc.): Traefik 2

### Issue information

**To Reproduce**

(Untested)
- Create a movie and a tv Plex library, each with a piece of content with identical titles
- Attempt to play the tv episode, observe that the movie plays instead
- Click the X to close the movie, note that the app switches to playing the tv episode as intended

**Describe your bug/issue**
Please describe the bug/your issue below. If applicable, add screenshots to help explain your problem.

I can do more testing if unable to reproduce, but I'm guessing that the bug is that the content is selcted by name/title, and not some other unique identifier within Plex, causing the movie to play instead of the tv episode (perhaps because "Movies" comes before "TV Shows" alphabetically?).

Curiously, this affected only 3 of 5 users in our party. All were using Firefox, one of those unaffected was streaming from a different, local server. I feel like there must be a factor I'm missing here that affected the 3, but I'm not sure what it could be.

**Comment by ttshivers** [comment]
Currently, the media selection is affected by the response times of servers which is why you are seeing differences in users. I have been working on a better media selection algorithm that will choose the same content if the user has access to the same server / content as the host.

**Comment by ttshivers** [comment]
#220 has guests play the same media (ratingKey) from the same server as the host if the guest can and then falls back to the media matching algorithm otherwise. The media matching algorithm is also improved in this PR.
