### ISSUE TITLE
Feature Request: Skip Intro for web player

### ISSUE THREAD

**Issue by chaehni** [synclounge/synclounge#211]
Please add the newly introduced "Skip Intro" [1] functionality to the web player.

[1] https://support.plex.tv/articles/skip-content/

**Comment by ttshivers** [comment]
If you can find some documentation or reverse engineer how to get this information from plex servers that would assist in supporting that feature.

**Comment by aRkker** [comment]
> If you can find some documentation or reverse engineer how to get this information from plex servers that would assist in supporting that feature.

Out of curiosity, I was looking into how Plex's own player figures out this stuff, and I noticed they have added a new query parameter to the onDeck path, as well as pretty much every other request as well sent to the URL plex.direct.

They add `&includeMarkers=1` to the requests, which in turn adds a new object to the response:

`"Marker":[{"type":"intro","startTimeOffset":1857,"endTimeOffset":87616}]}`

I hope this is of some use for developing the feature for those of us who like to binge-watch in groups

**Comment by ttshivers** [comment]
Thank you for this info @aRkker. I am interested in helping develop this feature. Would you be willing to join the discord so I can chat with you more about it.

**Comment by aRkker** [comment]
> Thank you for this info @aRkker. I am interested in helping develop this feature. Would you be willing to join the discord so I can chat with you more about it.
 
Absolutely, I'll see what I can do to help. I hopped on the Synclounge Discord under the same alias as here, feel free to shoot a message at me

**Comment by ttshivers** [comment]
Looks like it will be pretty easy to implement this feature.
