### ISSUE TITLE
SyncLounge player does not pick the same version of a clip automatically

### ISSUE THREAD

**Issue by Kidsnd274** [synclounge/synclounge#213]
### Issue information
If a movie has two or more versions (eg. 4K and 1080p versions), the same version would not be played between all of the viewers. For example, I would be hosting a room and viewing a 1080p version of a movie, but a friend would join and SyncLounge would automatically pick the 4K version. My server can't transcode 4K to 1080p fast enough and leads to constant buffering for my friend.

One way to fix this is to join the room, close the player and select the movie with the correct version. It would then sync up with the rest of the room while playing the correct version.

### Web App
**System Details**

- Operating System: Windows
- Web Browser name and version: Google Chrome 81.0.4044.138

**Plex Media Server details**

- Version: 1.19.3.2852
- Operating System (Windows/Linux/Mac): Windows
- Running in Docker? (Yes/No): No
- Location (Local/Remote): Local
- Remote Access Enabled (Yes/No)?: Yes

**Describe your bug/issue**
Please describe the bug/your issue below. If applicable, add screenshots to help explain your problem.

**Comment by ttshivers** [comment]
I have changed the auto media selection to pick the same ratingKey and mediaIndex as the host if the client has access to the same server as the host. This change along with others is part of a large cleanup I am doing but it is not done yet.

**Comment by ttshivers** [comment]
#220 has guests play the same media (ratingKey and mediaIndex) from the same server as the host if the guest can and then falls back to the media matching algorithm otherwise. The media matching algorithm is also improved in this PR.
