### ISSUE TITLE
Option for notifications when chats are received in the chat box

### ISSUE THREAD

**Issue by CLHatch** [synclounge/synclounge#219]
**Is your feature request related to a problem? Please describe.**
I often don't notice when a message is received in chat, because there is no sound.  And I would have no way of knowing a message was received if I go "full screen", because no sounds, and no "popup".

**Describe the solution you'd like**
We need an option for some sort of notification sound, and possibly a "tray notification" for chats if the video is in full screen.  These should be options, because some may find them annoying, especially with large rooms.  Possibly would want to add an option to "mute" sounds for certain "chatty" friends? :-D

**Describe alternatives you've considered**
I've considered using another chat program while watching with friends, but that sort of defeats the purpose of having built-in chat. :)

**Comment by ttshivers** [comment]
What do you think about using the standard [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/notification) to display chat messages?

**Comment by ttshivers** [comment]
I have implemented a notification feature in ttshivers/synclounge#33
