### ISSUE TITLE
Disallow use of players other than the Synclounge Player

### ISSUE THREAD

**Issue by strumtrupper** [synclounge/synclounge#222]
Due to issues I've experienced trying to use the other players, I'd like the ability to have my self hosted server default to the Synclounge Player and not give users the ability to select other players that they may have issues using.

An acceptable solution would be either skipping the screen entirely (preferred) or making it the only option by not displaying other players

![image](https://user-images.githubusercontent.com/30345685/87863291-93468000-c927-11ea-843c-ee1c18817547.png)

**Comment by gcordalis** [comment]
This is something we've discussed and will possibly show up in a future release

**Comment by ttshivers** [comment]
I can easily add a feature like this on my branch. I already have the web player chosen by default and can just get rid of the player selection with a config flag.

**Comment by strumtrupper** [comment]
@ttshivers sounds like I could do this on my instance. Would you be able to point me to the files I would need to modify on my instance to configure this? I'm not super practiced in JavaScript, but I would like to learn.

**Comment by ttshivers** [comment]
I have a config option that forces the slplayer on my fork. I'd recommend checking that out if you want that feature immediately. Join the discord and I can help walk you through a few things.

**Comment by strumtrupper** [comment]
I will take a look at that and definitely let you know if I have any questions.
