### ISSUE TITLE
Authentication Issue on new devices.

### ISSUE THREAD

**Issue by dethfactor** [synclounge/synclounge#228]
I'm running the latest version privately and any new devices that synclounge doesn't already have Authorized get rejected. When it goes through the plex authentication process,  "You are not authorized to access this server." is displayed when it finishes logging in. Even though the account does have access to the local server.

**Comment by ttshivers** [comment]
What config options are you using?

**Comment by dethfactor** [comment]
this is my settings.json:
```{
       "webroot":"",
       "serverroot":"",
       "accessUrl":"http://synclounge.mysite.com",
       "webapp_port":8280,
       "server_port":8281,
       "authentication":{
          "mechanism":"plex",
          "type":[
             "server"
          ],
          "authorized":[
             "40charactersypherofsomekind"
          ]
       },
       "servers":[
          {
             "name":"Watch Party",
             "location":"Hound Dog gunna eat that P***y",
             "url":"http://synclounge.mysite.com/slserver",
             "image":""
          }
       ],
       "autoJoin":false,
       "autoJoinServer":"",
       "autoJoinRoom":"",
       "autoJoinPassword":""
}```

**Comment by MagicalCodeMonkey** [comment]
Did you get the machine identifier following these instructions? 
http://docs.synclounge.tv/self-hosted/settings/#get-your-plex-servers-machine-identifier

**Comment by dethfactor** [comment]
So.. I did.. and then I remembered that I had migrated plex servers to a new operating system. So I went and regenerated the key and it's still saying I don't have access.

**Comment by dethfactor** [comment]
No.. but I just remembered I upgraded OS on my server and I guess my ID changed.. so I grabbed it and changed the config and now I'm in
