### ISSUE TITLE
SSO not working behind a reverse proxy

### ISSUE THREAD

**Issue by rg9400** [synclounge/synclounge#242]
### Web App
You can remove this section if your issue isn't related to the Web App

**System Details**

- Operating System: Docker (synclounge/synclounge, version 3.13.70, build https://github.com/synclounge/synclounge/commit/f88e7aa938628d2b19b5bd4b5ac8115eb648bc56)
- Web Browser name and version: Microsoft Edge Version 86.0.622.38 (Official build) beta (64-bit)

**Plex Media Server details**

- Version: 1.20.3.3421 
- Operating System (Windows/Linux/Mac): Windows Subsystem for Linux
- Running in Docker? (Yes/No): Yes
- Location (Local/Remote): Remote
- Remote Access Enabled (Yes/No)?: Yes

### Self-Hosting
Yes

**SyncLounge Details**

- Running in Docker? (Yes/No): Yes
- Using a Reverse Proxy (Yes/No): Yes
    If Yes, which Reverse Proxy (Nginx, Apache, Caddy, etc.): NGINX

### Issue information
It does not seem Synclounge is logging me in automatically when behind a reverse proxy. It works locally though. I can manually sign in.

I'm also running Organizr with Plex, Tautulli, and Ombi SSO enabled. These tokens are being stored in the browser, and I think the older version of the app used to pick one of these.

**To Reproduce**
1. Sign into Synclounge if not already signed in behind a RP
2. Sign out when using Synclounge behind a reverse proxy. It should automatically sign you back in if SSO is working
3. Try the same thing locally. It does work there.

**Comment by ttshivers** [comment]
Synclounge checks for the `mpt` cookie. I will see if Organizr still uses that. https://github.com/synclounge/synclounge/blob/master/src/views/SignIn.vue#L83

**Comment by ttshivers** [comment]
> Synclounge checks for the `mpt` cookie. I will see if Organizr still uses that. https://github.com/synclounge/synclounge/blob/master/src/views/SignIn.vue#L83

It appears that Organizr still uses this: https://github.com/causefx/Organizr/blob/9fa7496a0f5debb6eb8afaf848d122f103714848/api/functions/sso-functions.php#L6

**Comment by rg9400** [comment]
You are right, I logged out of Organizr and back in, and the SSO started working. Maybe the token just needed to be refreshed

**Comment by Cookie-Monster-Coder** [comment]
Can you post your synclounge nginx block? I can't seem to get SSO working.
