### ISSUE TITLE
"Cannot read property 'toString' of undefined" when attempting to access collections

### ISSUE THREAD

**Issue by VictorJosso** [synclounge/synclounge#283]
Hi, 

New to SyncLounge, just installed the docker version.
When I click on a collection (movie library), I got an error saying "Cannot read property 'toString' of undefined".

Thanks for your work.

**Comment by ttshivers** [comment]
Thanks for the bug report. We have an outstanding fix for this error while we work on supporting collections: https://github.com/synclounge/synclounge/pull/277

**Comment by VictorJosso** [comment]
Ok sorry, I didn't check pull requests...

**Comment by ttshivers** [comment]
Resolved in https://github.com/synclounge/synclounge/issues/283
