### ISSUE TITLE
Search Doesn't Work on Web App

### ISSUE THREAD

**Issue by Cimplex** [synclounge/synclounge#362]
### Web App
v4.1.14

**System Details**

- Operating System: Windows 10
- Web Browser name and version: Brave Version 1.16.76 Chromium: 86.0.4240.198 (Official Build) (64-bit)

### Issue information

**To Reproduce**

- Type in search
- Click item in drop down
- Nothing happens

**Describe your bug/issue**
Clicking on items in the search menu closes the menu, it should navigate to that item.

**Comment by ttshivers** [comment]
Thanks for reporting the issue. I can confirm that I am able to replicate the issue as well. Looking into the cause.

**Comment by ttshivers** [comment]
Looks like the issue was introducted with [Vuetify v2.3.17](https://github.com/vuetifyjs/vuetify/releases/tag/v2.3.17), most likely due to https://github.com/vuetifyjs/vuetify/pull/12566

**Comment by ttshivers** [comment]
Looks like there is an issue tracking this in vuetify: https://github.com/vuetifyjs/vuetify/issues/12586
Going to downgrade and block vuetify upgrades until that is fixed
