### ISSUE TITLE
Can no longer select subtitles in SyncLounge

### ISSUE THREAD

**Issue by ccristob** [synclounge/synclounge#824]
Unable to select subtitles in SyncLounge, happened as of a week ago. Any attempt to select a subtitle results in nothing happening and the selection stays at 'None'.

**Comment by ForThePasta** [comment]
> I am also having this issue as of late.



> Unable to select subtitles in SyncLounge, happened as of a week ago. Any attempt to select a subtitle results in nothing happening and the selection stays at 'None'.

A quote from one of the devs on their Discord: "We’ve seen your messages here but don’t have the time to look into it."

**Comment by Biyoni** [comment]
i too am having an issue with the core functionality of subtitles in a video player.

snarky comments will get the developer nowhere.

**Comment by ForThePasta** [comment]
> i too am having an issue with the core functionality of subtitles in a video player.
> 
> snarky comments will get the developer nowhere.

The issue for me seems to be somewhat fixed. I was able to watch Jojo and select Japanese audio and English subtitles, and whilst the player still showed none being selected, both me and my girlfriend were able to see the subtitles.

**Comment by ccristob** [comment]
> 
> 
> > i too am having an issue with the core functionality of subtitles in a video player.
> > snarky comments will get the developer nowhere.
> 
> The issue for me seems to be somewhat fixed. I was able to watch Jojo and select Japanese audio and English subtitles, and whilst the player still showed none being selected, both me and my girlfriend were able to see the subtitles.

Still not working for me, same issue as originally described

**Comment by TheCzechBagel** [comment]
My friend keeps lying to me about this issue but I know it is his fault. If you see this Antony. Fuck you

**Comment by guiscaranse** [comment]
I've downgraded to Plex [1.24.3.5033-757abe6b4](https://hub.docker.com/layers/plexinc/pms-docker/1.24.3.5033-757abe6b4/images/sha256-3a94815bbf40ee2a0993ebbd5878993ad7d81b1550a1e890f52740cb56886232?context=explore) and seems to solve the issue. If you can't downgrade for whatever reason, on `Settings` enable `Force Plex to Burn Subtitles` and it will enable for whatever default subtitles you have on plex.

**Comment by ccristob** [comment]
> 

Unfortunately not really a good compromise for me since that would mean I'd have to transcode for everyone watching together when burning in subs

**Comment by ForThePasta** [comment]
> I've downgraded to Plex [1.24.3.5033-757abe6b4](https://hub.docker.com/layers/plexinc/pms-docker/1.24.3.5033-757abe6b4/images/sha256-3a94815bbf40ee2a0993ebbd5878993ad7d81b1550a1e890f52740cb56886232?context=explore) and seems to solve the issue. If you can't downgrade for whatever reason, on `Settings` enable `Force Plex to Burn Subtitles` and it will enable for the default subtitles you have on plex.

Can confirm this fixed the issue 100% for me.

**Comment by marissa999** [comment]
> If you can't downgrade for whatever reason, on `Settings` enable `Force Plex to Burn Subtitles` and it will enable for the default subtitles you have on plex.

It's very good to know that burning subtitles is a workaround. But I assume that this will increase the server load quite a bit and might therefore not always be a solution.

**Comment by lilchancep** [comment]
@ttshivers You got anymore tricks up your sleeve?
